---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/achievements/":
    post:
      summary: Create an achievement
      tags:
      - Achievement
      parameters: []
      responses:
        '201':
          description: achievement created
          content:
            application/json:
              example:
                id: 1
                user_id: 1
                achievement_identifier: 42
                created_at: '2022-01-09T14:28:20.120Z'
                updated_at: '2022-01-09T14:28:20.120Z'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                achievement_identifier:
                  type: string
              required:
              - achievement_identifier
    get:
      summary: Get all achievements
      tags:
      - Achievement
      responses:
        '200':
          description: get all achievement
          content:
            application/json:
              example:
              - id: 2
                user_id: 2
                achievement_identifier: 536
                created_at: '2022-01-09T14:28:20.383Z'
                updated_at: '2022-01-09T14:28:20.383Z'
              - id: 3
                user_id: 2
                achievement_identifier: 258
                created_at: '2022-01-09T14:28:20.386Z'
                updated_at: '2022-01-09T14:28:20.386Z'
  "/api/v1/achievements/{id}/":
    delete:
      summary: delete an achievement
      tags:
      - Achievement
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: achievement successfully deleted
        '404':
          description: Not found 404
          content:
            application/json:
              example:
                status: Not Found 404
    get:
      summary: Retrieve an achievement
      tags:
      - Achievement
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: achievement found
          content:
            application/json:
              example:
                id: 6
                user_id: 5
                achievement_identifier: 310
                created_at: '2022-01-09T14:28:21.207Z'
                updated_at: '2022-01-09T14:28:21.207Z'
        '404':
          description: achievement not found
          content:
            application/json:
              example:
                status: Not Found 404
  "/api/v1/auth/":
    post:
      summary: Create a user
      tags:
      - Auth
      parameters: []
      security: []
      responses:
        '200':
          description: user created
          content:
            application/json:
              example:
                status: success
                data:
                  id: 7
                  username: reuben.boyer#7
                  email: layla.gerhold@murazik.io
                  email_validated: false
                  preferred_lang: ru_RU
                  avatar_id: 
                  coins: 0
                  fantasy_points: 0
                  created_at: '2022-01-09T14:28:22.008Z'
                  updated_at: '2022-01-09T14:28:22.008Z'
                  provider: email
                  uid: layla.gerhold@murazik.io
                  allow_password_change: false
        '422':
          description: incorrect email or username; email and/or username has already
            been taken
          content:
            application/json:
              example:
                status: error
                data:
                  id: 
                  username: scot_wiegand#12
                  email: ron
                  email_validated: false
                  preferred_lang: ru_RU
                  avatar_id: 
                  coins: 0
                  fantasy_points: 0
                  created_at: 
                  updated_at: 
                  provider: email
                  uid: ''
                  allow_password_change: false
                errors:
                  email:
                  - is not an email
                  full_messages:
                  - Email is not an email
                  username:
                  - is too short (minimum is 3 characters)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
              - username
              - email
              - password
    delete:
      summary: Delete a user
      tags:
      - Auth
      responses:
        '200':
          description: user successfully deleted
          content:
            application/json:
              example:
                status: success
                message: Account with UID 'dagny_lind@ward-hoeger.name' has been destroyed.
        '404':
          description: credentials are invalid
          content:
            application/json:
              example:
                success: false
                errors:
                - Unable to locate account for destruction.
                status: error
  "/api/v1/auth/sign_in":
    post:
      summary: Sign in
      tags:
      - Auth
      parameters: []
      security: []
      responses:
        '200':
          description: logged in
          headers:
            access-token:
              type: string
              description: Access token
            client:
              type: string
              description: Client token
            uid:
              type: string
              description: User identifier
            expiry:
              type: string
              description: Token expiry timestamp
          content:
            application/json:
              example:
                data:
                  email: chris@quigley-lindgren.net
                  email_validated: false
                  id: 12
                  fantasy_points: 0
                  coins: 0
                  uid: chris@quigley-lindgren.net
                  username: chauncey#15
                  preferred_lang: ru_RU
                  avatar_id: 
                  provider: email
                  allow_password_change: false
        '401':
          description: credentials are invalid; email is not confirmed
          content:
            application/json:
              example:
                success: false
                errors:
                - Invalid login credentials. Please try again.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/api/v1/auth/sign_out":
    delete:
      summary: Sign out
      tags:
      - Auth
      responses:
        '200':
          description: signed out
          content:
            application/json:
              example:
                success: true
        '404':
          description: credentials are invalid
          content:
            application/json:
              example:
                success: false
                errors:
                - User was not found or was not logged in.
  "/api/v1/auth/validate_token":
    get:
      summary: Validate token
      tags:
      - Auth
      responses:
        '200':
          description: token is valid
          content:
            application/json:
              example:
                success: true
                data:
                  id: 20
                  username: lourdes_ankunding#23
                  email: denny_cormier@wuckert.info
                  email_validated: false
                  preferred_lang: ru_RU
                  avatar_id: 
                  coins: 0
                  fantasy_points: 0
                  provider: email
                  uid: denny_cormier@wuckert.info
                  allow_password_change: false
        '401':
          description: credentials are invalid
          content:
            application/json:
              example:
                success: false
                errors:
                - Invalid login credentials
  "/api/v1/auth/confirmation":
    post:
      summary: Resend confirmation
      tags:
      - Auth
      parameters: []
      security: []
      responses:
        '200':
          description: confirmation sent
          content:
            application/json:
              example:
                success: true
                message: An email has been sent to 'santo.moore@lynch-von.biz' containing
                  instructions for confirming your account.
        '404':
          description: email is invalid
          content:
            application/json:
              example:
                success: false
                errors:
                - Unable to find user with email 'thaddeus_ankunding@schimmel.co'.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required:
              - email
  "/api/v1/auth/password":
    put:
      summary: Change password
      tags:
      - Auth
      description: Change password
      parameters: []
      responses:
        '200':
          description: password has been updated
          content:
            application/json:
              example:
                success: true
                data:
                  email: caleb_bradtke@auer.info
                  email_validated: false
                  id: 24
                  fantasy_points: 0
                  coins: 0
                  uid: caleb_bradtke@auer.info
                  username: jerrold#27
                  preferred_lang: ru_RU
                  avatar_id: 
                  created_at: '2022-01-09T14:28:29.095Z'
                  updated_at: '2022-01-09T14:28:29.361Z'
                  provider: email
                  allow_password_change: false
                message: Your password has been successfully updated.
        '422':
          description: must fill out the fields password; doesn't match password
          content:
            application/json:
              example:
                success: false
                errors:
                  password_confirmation:
                  - doesn't match Password
                  full_messages:
                  - Password confirmation doesn't match Password
        '401':
          description: unauthorized
          content:
            application/json:
              example:
                success: false
                errors:
                - Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                password_confirmation:
                  type: string
              required:
              - password
              - password_confirmation
  "/api/v1/auth/password/":
    put:
      summary: Change password with reset_password_token
      tags:
      - Auth
      description: Set password that was reset
      parameters: []
      security: []
      responses:
        '200':
          description: password has been updated
          content:
            application/json:
              example:
                success: true
                data:
                  email: lindsey_heidenreich@fahey.info
                  email_validated: false
                  id: 28
                  fantasy_points: 0
                  coins: 0
                  uid: lindsey_heidenreich@fahey.info
                  username: bradford.stamm#31
                  preferred_lang: ru_RU
                  avatar_id: 
                  created_at: '2022-01-09T14:28:30.678Z'
                  updated_at: '2022-01-09T14:28:31.048Z'
                  provider: email
                  allow_password_change: false
                message: Your password has been successfully updated.
        '422':
          description: must fill out the fields password; doesn't match password
          content:
            application/json:
              example:
                success: false
                errors:
                  password_confirmation:
                  - doesn't match Password
                  full_messages:
                  - Password confirmation doesn't match Password
        '401':
          description: unauthorized
          content:
            application/json:
              example:
                success: false
                errors:
                - Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                password_confirmation:
                  type: string
                reset_password_token:
                  type: string
              required:
              - password
              - password_confirmation
              - reset_password_token
    post:
      summary: Send a password reset email
      tags:
      - Auth
      parameters: []
      security: []
      responses:
        '200':
          description: email has been sent
          content:
            application/json:
              example:
                success: true
                message: An email has been sent to 'saturnina@graham.co' containing
                  instructions for resetting your password.
        '401':
          description: missing email
          content:
            application/json:
              example:
                success: false
                errors:
                - You must provide an email address.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required:
              - email
  "/api/v1/briefcases/":
    post:
      summary: Create a briefcase
      tags:
      - Briefcase
      responses:
        '201':
          description: briefcase created
          content:
            application/json:
              example:
                id: 1
                expiring_at: '2022-01-16T14:28:32.929Z'
                user_id: 34
                created_at: '2022-01-09T14:28:32.943Z'
                updated_at: '2022-01-09T14:28:32.943Z'
    get:
      summary: Get all briefcases
      tags:
      - Briefcase
      responses:
        '200':
          description: get all briefcases for current user
          content:
            application/json:
              example:
              - id: 2
                expiring_at: '2022-11-18T00:00:00.000Z'
                user_id: 35
                created_at: '2022-01-09T14:28:33.205Z'
                updated_at: '2022-01-09T14:28:33.205Z'
  "/api/v1/briefcases/{id}/":
    delete:
      summary: delete a briefcase
      tags:
      - Briefcase
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: briefcase successfully deleted
        '404':
          description: Not found 404
          content:
            application/json:
              example:
                status: Not Found 404
    get:
      summary: Retrieve a briefcase
      tags:
      - Briefcase
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: briefcase connected with current user found
          content:
            application/json:
              example:
                id: 5
                expiring_at: '2022-03-17T00:00:00.000Z'
                user_id: 38
                created_at: '2022-01-09T14:28:34.035Z'
                updated_at: '2022-01-09T14:28:34.035Z'
        '404':
          description: briefcase not found
          content:
            application/json:
              example:
                status: Not Found 404
    patch:
      summary: Update a briefcase
      tags:
      - Briefcase
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '404':
          description: briefcase not found
          content:
            application/json:
              example:
                status: Not Found 404
        '201':
          description: briefcase updated
          content:
            application/json:
              example:
                id: 9
                expiring_at: '2022-03-01T00:00:00.000Z'
                user_id: 42
                created_at: '2022-01-09T14:28:35.157Z'
                updated_at: '2022-01-09T14:28:35.157Z'
        '400':
          description: stock not found
          content:
            application/json:
              example:
                status: Bad Request ( Stock not Found )
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                stock_id:
                  type: integer
                add:
                  type: boolean
  "/api/v1/briefcases/{id}/stocks/":
    get:
      summary: Get stocks by briefcase id
      tags:
      - Briefcase
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: stocks in briefcase
          content:
            application/json:
              example:
              - id: 5
                name: opj37qr
                created_at: '2022-01-09T14:28:35.719Z'
                updated_at: '2022-01-09T14:28:35.719Z'
              - id: 6
                name: oh4a2
                created_at: '2022-01-09T14:28:35.721Z'
                updated_at: '2022-01-09T14:28:35.721Z'
              - id: 7
                name: ntkjt91l
                created_at: '2022-01-09T14:28:35.724Z'
                updated_at: '2022-01-09T14:28:35.724Z'
        '404':
          description: not found
          content:
            application/json:
              example:
                status: Not Found 404
  "/api/v1/contest_applications/":
    post:
      summary: Create a contest application
      tags:
      - ContestApplication
      parameters: []
      responses:
        '201':
          description: contest application created
          content:
            application/json:
              example:
                id: 1
                user_id: 47
                contest_id: 1
                final_position: 
                coins_delta: 
                fantasy_points_delta: 
                created_at: '2022-01-09T14:28:36.829Z'
                updated_at: '2022-01-09T14:28:36.829Z'
        '400':
          description: contest application created
          content:
            application/json:
              example:
                error: An Error occurred ["User must exist"]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                contest_id:
                  type: integer
              required:
              - user_id
              - contest_id
    get:
      summary: Get contest applications
      parameters:
      - name: contest_id
        in: query
        required: false
        schema:
          type: integer
      tags:
      - ContestApplication
      responses:
        '200':
          description: |-
            get all contest applications for current user if contest_id not set otherwise returns all
                                   contest applications by contest_id
          content:
            application/json:
              example:
              - id: 3
                user_id: 54
                contest_id: 6
                final_position: 
                coins_delta: 
                fantasy_points_delta: 
                created_at: '2022-01-09T14:28:38.408Z'
                updated_at: '2022-01-09T14:28:38.408Z'
  "/api/v1/contest_applications/{id}/":
    delete:
      summary: delete a contest application
      tags:
      - ContestApplication
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: contest application successfully deleted
        '404':
          description: contest application not found
          content:
            application/json:
              example:
                status: Not Found 404
    get:
      summary: Retrieve a contest application
      tags:
      - ContestApplication
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: contest application found
          content:
            application/json:
              example:
                id: 6
                user_id: 57
                contest_id: 12
                final_position: 
                coins_delta: 
                fantasy_points_delta: 
                created_at: '2022-01-09T14:28:39.265Z'
                updated_at: '2022-01-09T14:28:39.265Z'
        '404':
          description: contest application not found
          content:
            application/json:
              example:
                status: Not Found 404
  "/api/v1/contest_application_stocks/":
    post:
      summary: Create a contest application stock
      tags:
      - ContestApplicationStock
      parameters: []
      responses:
        '201':
          description: contest application stock created
          content:
            application/json:
              example:
                id: 1
                contest_application_id: 8
                stock_id: 8
                multiplier: '10.0'
                reg_price: 
                final_price: 
                created_at: '2022-01-09T14:28:40.362Z'
                updated_at: '2022-01-09T14:28:40.362Z'
        '400':
          description: contest application stock created
          content:
            application/json:
              example:
                error: An Error occurred ["Stock must exist"]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                stock_id:
                  type: integer
                contest_application_id:
                  type: integer
                multiplier:
                  type: integer
              required:
              - multiplier
              - stock_id
              - contest_application_id
    get:
      summary: Get contest application stock stocks
      tags:
      - ContestApplicationStock
      parameters:
      - name: contest_id
        in: query
        required: false
        schema:
          type: integer
      responses:
        '200':
          description: |-
            get all contest application stocks if contest_id not set otherwise returns all
                                   contest applications by contest_id
          content:
            application/json:
              example:
              - id: 4
                contest_application_id: 12
                stock_id: 12
                multiplier: '1.0'
                reg_price: '2003.3053'
                final_price: 
                created_at: '2022-01-09T14:28:42.238Z'
                updated_at: '2022-01-09T14:28:42.238Z'
                stock:
                  id: 12
                  name: DIS
                  created_at: '2022-01-09T14:28:41.972Z'
                  updated_at: '2022-01-09T14:28:41.972Z'
              - id: 5
                contest_application_id: 13
                stock_id: 13
                multiplier: '1.0'
                reg_price: '819.9968'
                final_price: 
                created_at: '2022-01-09T14:28:42.243Z'
                updated_at: '2022-01-09T14:28:42.243Z'
                stock:
                  id: 13
                  name: MSFT
                  created_at: '2022-01-09T14:28:42.232Z'
                  updated_at: '2022-01-09T14:28:42.232Z'
  "/api/v1/contest_application_stocks/{id}/":
    delete:
      summary: delete a contest application stock
      tags:
      - ContestApplicationStock
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: contest application successfully deleted
        '404':
          description: contest application not found
          content:
            application/json:
              example:
                status: Not Found 404
    get:
      summary: Retrieve a contest application stock
      tags:
      - ContestApplicationStock
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: contest application stock found
          content:
            application/json:
              example:
                id: 8
                contest_application_id: 19
                stock_id: 19
                multiplier: '1.0'
                reg_price: '2035.7161'
                final_price: 
                created_at: '2022-01-09T14:28:44.659Z'
                updated_at: '2022-01-09T14:28:44.659Z'
        '404':
          description: contest application stock not found
          content:
            application/json:
              example:
                status: Not Found 404
  "/api/v1/contests/":
    post:
      summary: Create a contest
      tags:
      - Contest
      parameters: []
      responses:
        '201':
          description: contest created
          content:
            application/json:
              example:
                id: 29
                reg_ending_at: '2022-01-09T00:00:00.000Z'
                summarizing_at: '2022-01-14T00:00:00.000Z'
                status: created
                coins_entry_fee: 8888474518
                max_fantasy_points_threshold: 4543294160
                use_briefcase_only: true
                direction_strategy: single_per_user
                fixed_direction_up: 
                use_disabled_multipliers: false
                use_inverted_stock_prices: false
                created_at: '2022-01-09T14:28:46.001Z'
                updated_at: '2022-01-09T14:28:46.001Z'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                coins_entry_fee:
                  type: integer
                direction_strategy:
                  type: string
                fixed_direction_up:
                  type: boolean
                max_fantasy_points_threshold:
                  type: integer
                reg_ending_at:
                  type: string
                status:
                  type: string
                summarizing_at:
                  type: string
                use_briefcase_only:
                  type: boolean
                use_disabled_multipliers:
                  type: boolean
                use_inverted_stock_prices:
                  type: boolean
              required:
              - coins_entry_fee
              - direction_strategy
              - fixed_direction_up
              - max_fantasy_points_threshold
              - reg_ending_at
              - status
              - summarizing_at
              - use_briefcase_only
              - use_disabled_multipliers
              - use_inverted_stock_prices
    get:
      summary: Get contests
      parameters:
      - name: fixed_direction_up
        in: query
        required: false
        nullable: true
        schema:
          type: boolean
      - name: use_briefcase_only
        in: query
        required: false
        nullable: true
        schema:
          type: boolean
      - name: use_disabled_multipliers
        in: query
        required: false
        nullable: true
        schema:
          type: boolean
      - name: use_inverted_stock_prices
        in: query
        required: false
        nullable: true
        schema:
          type: boolean
      - name: status
        in: query
        required: false
        nullable: true
        schema:
          type: string
      - name: direction_strategy
        in: query
        required: false
        nullable: true
        schema:
          type: string
      - name: coins_entry_fee_min_edge
        in: query
        required: false
        nullable: true
        schema:
          type: integer
      - name: coins_entry_fee_max_edge
        in: query
        required: false
        nullable: true
        schema:
          type: integer
      - name: max_fantasy_points_threshold
        in: query
        required: false
        nullable: true
        schema:
          type: integer
      tags:
      - Contest
      responses:
        '200':
          description: get contests
          content:
            application/json:
              example:
              - id: 92
                reg_ending_at: '2022-01-10T00:00:00.000Z'
                summarizing_at: '2022-01-16T00:00:00.000Z'
                status: created
                coins_entry_fee: 9353932668
                max_fantasy_points_threshold: 2205519036
                use_briefcase_only: true
                direction_strategy: fixed
                fixed_direction_up: false
                use_disabled_multipliers: false
                use_inverted_stock_prices: false
                created_at: '2022-01-09T14:28:48.144Z'
                updated_at: '2022-01-09T14:28:48.144Z'
  "/api/v1/contests/{id}/":
    delete:
      summary: delete a contest
      tags:
      - Contest
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: contest successfully deleted
        '404':
          description: contest not found
          content:
            application/json:
              example:
                status: Not Found 404
    get:
      summary: Retrieve a contest
      tags:
      - Contest
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: contest found
          content:
            application/json:
              example:
                id: 96
                reg_ending_at: '2022-01-09T00:00:00.000Z'
                summarizing_at: '2022-01-15T00:00:00.000Z'
                status: created
                coins_entry_fee: 7515229348
                max_fantasy_points_threshold: 6078114524
                use_briefcase_only: true
                direction_strategy: single_per_user
                fixed_direction_up: 
                use_disabled_multipliers: false
                use_inverted_stock_prices: false
                created_at: '2022-01-09T14:28:48.975Z'
                updated_at: '2022-01-09T14:28:48.975Z'
        '404':
          description: contest not found
          content:
            application/json:
              example:
                status: Not Found 404
  "/api/v1/stocks/":
    post:
      summary: Create a stock
      tags:
      - Stock
      parameters: []
      responses:
        '201':
          description: stock created
          content:
            application/json:
              example:
                id: 22
                name: GOOGL
                created_at: '2022-01-09T14:28:50.087Z'
                updated_at: '2022-01-09T14:28:50.087Z'
        '400':
          description: stock not created
          content:
            application/json:
              example:
                error: An Error occurred Finnhub couldn't find symbol t1v
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
    get:
      summary: Get stocks
      tags:
      - Stock
      responses:
        '200':
          description: get all stocks
          content:
            application/json:
              example:
              - id: 25
                name: T
                created_at: '2022-01-09T14:28:54.815Z'
                updated_at: '2022-01-09T14:28:54.815Z'
  "/api/v1/stocks/{id}/":
    delete:
      summary: delete a stock
      tags:
      - Stock
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: stock successfully deleted
        '404':
          description: Not found 404
          content:
            application/json:
              example:
                status: Not Found 404
    get:
      summary: Retrieve a stock
      tags:
      - Stock
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: stock found
          content:
            application/json:
              example:
                id: 28
                name: BKNG
                created_at: '2022-01-09T14:28:55.665Z'
                updated_at: '2022-01-09T14:28:55.665Z'
        '404':
          description: stock not found
          content:
            application/json:
              example:
                status: Not Found 404
  "/api/v1/stocks/suggestions/":
    get:
      summary: Get 10 stocks
      tags:
      - Stock
      responses:
        '200':
          description: get 10 stocks
          content:
            application/json:
              example:
              - id: 30
                name: 7x61rc
              - id: 38
                name: ot8bd1lm
              - id: 39
                name: bwek
              - id: 46
                name: j0k9acm
              - id: 41
                name: sys7i
              - id: 57
                name: kb3qy
              - id: 34
                name: 43r
              - id: 52
                name: 6zh
              - id: 59
                name: s00cm
              - id: 47
                name: hb5qrjmu
  "/api/v1/stocks/name/{name}/":
    get:
      summary: Retrieve a stock by name
      tags:
      - Stock
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: stock found
          content:
            application/json:
              example:
                id: 60
                name: WMT
                created_at: '2022-01-09T14:28:56.818Z'
                updated_at: '2022-01-09T14:28:56.818Z'
        '404':
          description: stock not found
          content:
            application/json:
              example:
                status: Not Found 404
  "/api/v1/users/":
    get:
      summary: Get users
      tags:
      - User
      responses:
        '200':
          description: get all users
          content:
            application/json:
              example:
              - id: 107
                username: sydney#110
                email: luigi.spencer@hayes.name
                email_validated: false
                preferred_lang: ru_RU
                avatar_id: 
                coins: 0
                fantasy_points: 0
                created_at: '2022-01-09T14:28:57.612Z'
                updated_at: '2022-01-09T14:28:57.618Z'
                provider: email
                uid: luigi.spencer@hayes.name
                allow_password_change: false
    patch:
      summary: update a user
      tags:
      - User
      parameters: []
      responses:
        '201':
          description: user updated
          content:
            application/json:
              example:
                username: test
                coins: 3
                email: trista@simonis.name
                email_validated: false
                id: 108
                fantasy_points: 0
                uid: trista@simonis.name
                preferred_lang: ru_RU
                avatar_id: 
                created_at: '2022-01-09T14:28:57.887Z'
                updated_at: '2022-01-09T14:28:57.906Z'
                provider: email
                allow_password_change: false
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: email
                preferred_lang:
                  type: string
                fantasy_points:
                  type: integer
                coins:
                  type: integer
  "/api/v1/users/{id}/":
    get:
      summary: Retrieve a user
      tags:
      - User
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: user found
          content:
            application/json:
              example:
                id: 109
                username: janey#112
                email: sachiko.erdman@schulist.io
                email_validated: false
                preferred_lang: ru_RU
                avatar_id: 
                coins: 0
                fantasy_points: 0
                created_at: '2022-01-09T14:28:58.164Z'
                updated_at: '2022-01-09T14:28:58.164Z'
                provider: email
                uid: sachiko.erdman@schulist.io
                allow_password_change: false
        '404':
          description: stock not found
  "/api/v1/users/contest_applications/{id}/":
    get:
      summary: Get contest application for current user by id
      tags:
      - User
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: get contest application by id
          content:
            application/json:
              example:
                id: 22
                user_id: 113
                contest_id: 98
                final_position: 
                coins_delta: 
                fantasy_points_delta: 
                created_at: '2022-01-09T14:28:59.218Z'
                updated_at: '2022-01-09T14:28:59.218Z'
  "/api/v1/users/scoreboard/":
    get:
      summary: Get users ordered by fantasy_points
      tags:
      - User
      responses:
        '200':
          description: get users
          content:
            application/json:
              example:
              - id: 115
                username: genaro.rutherford#118
                email: salvador@smitham.name
                email_validated: true
                preferred_lang: ru_RU
                avatar_id: 
                coins: 6189521438
                fantasy_points: 9833753990
                created_at: '2022-01-09T14:28:59.743Z'
                updated_at: '2022-01-09T14:28:59.743Z'
                provider: email
                uid: salvador@smitham.name
                allow_password_change: false
              - id: 117
                username: carmelo_friesen#120
                email: horacio@donnelly.net
                email_validated: true
                preferred_lang: ru_RU
                avatar_id: 
                coins: 3240329506
                fantasy_points: 7709392132
                created_at: '2022-01-09T14:29:00.246Z'
                updated_at: '2022-01-09T14:29:00.246Z'
                provider: email
                uid: horacio@donnelly.net
                allow_password_change: false
              - id: 118
                username: elias.yundt#121
                email: julietta@russel-hickle.io
                email_validated: true
                preferred_lang: ru_RU
                avatar_id: 
                coins: 6844670479
                fantasy_points: 4304818604
                created_at: '2022-01-09T14:29:00.498Z'
                updated_at: '2022-01-09T14:29:00.498Z'
                provider: email
                uid: julietta@russel-hickle.io
                allow_password_change: false
              - id: 114
                username: shenita.schamberger#117
                email: porter@jaskolski.info
                email_validated: true
                preferred_lang: ru_RU
                avatar_id: 
                coins: 6021715054
                fantasy_points: 2034163228
                created_at: '2022-01-09T14:28:59.491Z'
                updated_at: '2022-01-09T14:28:59.491Z'
                provider: email
                uid: porter@jaskolski.info
                allow_password_change: false
              - id: 116
                username: temeka#119
                email: bertram_hilpert@dach-bechtelar.name
                email_validated: true
                preferred_lang: ru_RU
                avatar_id: 
                coins: 8041989867
                fantasy_points: 1596387665
                created_at: '2022-01-09T14:28:59.994Z'
                updated_at: '2022-01-09T14:28:59.994Z'
                provider: email
                uid: bertram_hilpert@dach-bechtelar.name
                allow_password_change: false
consumes:
- application/json
produces:
- application/json
servers:
- url: "{defaultHost}"
  variables:
    defaultHost:
      default: http://localhost:3000
components:
  securitySchemes:
    accessToken:
      type: apiKey
      in: header
      name: Access-Token
    client:
      type: apiKey
      in: header
      name: Client
    uid:
      type: apiKey
      in: header
      name: UID
security:
- accessToken: []
  client: []
  uid: []
